version: '3.8'

services:
  app:
    container_name: splitwise-messages
    build: .
    restart: unless-stopped
    command: uvicorn app:app --proxy-headers --host 0.0.0.0 --port 8000
    ports:
      - 8008:8000
    env_file:
      - .env
