version: '3.8'

services:
  web:
    container_name: transactions-web
    build: .
    restart: unless-stopped
    command: uvicorn web.app:app --proxy-headers --host 0.0.0.0 --port 8000
    ports:
      - 8008:8000
    env_file:
      - .env
    volumes:
      - ./data:/app/data

  bot:
    container_name: transactions-bot
    build: .
    restart: unless-stopped
    command: python bot/app.py
    env_file:
      - .env
    volumes:
      - ./data:/app/data
