version: '3.8'

services:
  app:
    container_name: splitwise-messages
    build: .
    restart: unless-stopped
    command: uvicorn app:app --host 0.0.0.0 --port 8000
    ports:
      - 8008:8000
    environment:
      TELEGRAM_TOKEN: "$TELEGRAM_TOKEN"
      TELEGRAM_USER_ID: "$TELEGRAM_USER_ID"
      SPLITWISE_USER_ID: "$SPLITWISE_USER_ID"
