"""add account_id

Revision ID: d22f1e2f8e22
Revises: 2db11f34c868
Create Date: 2022-02-05 17:58:17.345468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd22f1e2f8e22'
down_revision = '2db11f34c868'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('account_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'account_id')
    # ### end Alembic commands ###
